language: node_js
node_js:
  - 6
cache:
  directories:
    - front-end/node_modules
script:
  - cd front-end
  - yarn
  - yarn build
  - yarn test --coverage --coverageReporters=text-lcov && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
