export default
{
	UPDATE_BALANCE: 'wallet/UPDATE_BALANCE',
	TRANSACTION_STATUS_UPDATE: 'wallet/TRANSACTION_STATUS_UPDATE',
	CHANGE_AMOUNT: 'wallet/CHANGE_AMOUNT',
	CHANGE_RECEIVER: 'wallet/CHANGE_RECEIVER',
};
