export default
{
	UPDATE_BALANCE: 'wallet/UPDATE_BALANCE',
	BALANCE_UPDATE_FAILED: 'wallet/BALANCE_UPDATE_FAILED',
	TRANSACTION_STATUS_UPDATE: 'wallet/TRANSACTION_STATUS_UPDATE',
	CHANGE_AMOUNT: 'wallet/CHANGE_AMOUNT',
	INVALID_AMOUNT_ERROR: 'wallet/INVALID_AMOUNT_ERROR',
	CHANGE_RECEIVER: 'wallet/CHANGE_RECEIVER',
	INVALID_RECEIVER_ERROR: 'wallet/INVALID_RECEIVER_ERROR',
	START_TRANSACTION: 'wallet/START_TRANSACTION',
	TRANSACTION_SUCCESS: ' wallet/TRANSACTION_FINISHED',
};
