export default
{
	LOG_IN: 'auth/LOG_IN',
	LOG_OUT:'auth/LOG_OUT',
	CHANGE_USERNAME:'auth/CHANGE_USERNAME',
	PROGRESS_UPDATE: 'auth/PROGRESS_UPDATE',
	LOGIN_ATTEMPT_FINISHED: 'auth/LOGIN_ATTEMPT_FINISHED'
};
