export default
{
	LOG_IN: 'auth/LOG_IN',
	LOG_OUT: 'auth/LOG_OUT',
	CHANGE_USERNAME: 'auth/CHANGE_USERNAME',
	PROGRESS_UPDATE: 'auth/PROGRESS_UPDATE',
	LOGIN_ATTEMPT_FINISHED: 'auth/LOGIN_ATTEMPT_FINISHED',
	SET_USERNAME_ERROR: 'auth/SET_USERNAME_ERROR',
	SET_PASSWORD_ERROR: 'auth/SET_PASSWORD_ERROR',
	CLEAR_PASSWORD_ERROR: 'auth/CLEAR_PASSWORD_ERROR',
};
